proyectoTablero/apps/tablero/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import crearNota, Notas, editarNota, eliminarNota

#urlpatterns = [
#    path('crear_nota/', crearNota, name='crear_nota'),
#    path('notas/', Notas, name='notas' ),
#    path('editar_nota/<int:id>', editarNota, name= 'editar_nota'),
#    path('eliminar_nota/<int:id>', eliminarNota, name='eliminar_nota')
#]

urlpatterns = [
    path('crear_nota/', login_required(crearNota), name='crear_nota'),
    path('notas/', login_required(Notas), name='notas'),
    path('editar_nota/<int:id>', login_required(editarNota), name='editar_nota'),
    path('eliminar_nota/<int:id>', login_required(eliminarNota), name='eliminar_nota'),
]

proyectoTablero/apps/usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [        
    path('registro/', views.registro, name='registro'),
    path('login/', views.iniciar_sesion, name='login'),
    path('logout/', views.logout, name='logout'),
]

proyectoTablero/proyectoTablero/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.tablero.views import Home, Notas
from apps.usuarios import views as usuarios_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', Home, name='index'),
    path('tablero/', include(('apps.tablero.urls','tablero'))),
    path('usuarios/', include(('apps.usuarios.urls','usuarios'))),
    path('notas/', Notas, name='notas'),
    path('usuarios/registro/', usuarios_views.registro, name='registro'),
    path('usuarios/login/', usuarios_views.iniciar_sesion, name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoTablero/apps/tablero/models.py
from django.db import models
from proyectoTablero import settings

class Nota(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=50, blank=False, null=False)
    contenido = models.TextField(blank=False, null=False)
    imagen = models.ImageField(upload_to='notas_imagenes/', null=True, blank=True)
    COLORES = [
        ('#EA9E19', 'Amarillo'),  
        ('#54ea19', 'Verde'), 
        ('#19b6ea', 'Azul'),  
    ]
    color = models.CharField(max_length=20, choices=COLORES, default='#ffffff', null=True, blank=True)

    def __str__(self):
        return self.titulo

proyectoTablero/apps/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser (AbstractUser):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    apellido = models.CharField(max_length=50, blank=False, null=False)
    fecha_nacimiento = models.DateField(null=True, blank=True)

    
    def __str__(self):
        return self.nombre  # Devuelve el nombre de usuario al imprimir el objeto

proyectoTablero/apps/tablero/forms.py
from django import forms
from .models import Nota

class NotaForm(forms.ModelForm):
    # Campo para la imagen
    imagen = forms.ImageField(required=False)
    
    # Campo para el color
    COLORES = [
        ('#EA9E19', 'Amarillo'),  
        ('#54ea19', 'Verde'), 
        ('#19b6ea', 'Azul'),  
    ]
    color = forms.ChoiceField(choices=COLORES, initial='#ffffff')

    class Meta:
        model = Nota    
        fields = ('titulo', 'contenido', 'imagen', 'color')

proyectoTablero/apps/usuarios/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        #fields = ('username', 'password1', 'password2', 'fecha_nacimiento')
        fields = ['username', 'fecha_nacimiento', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden. Por favor, inténtalo de nuevo.")

        return cleaned_data

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')

proyectoTablero/apps/tablero/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from .forms import NotaForm
from .models import Nota

# Esta función nos carga el arhivo raiz 
#  es la vista principal de la aplicación 
def Home(request):
    return render(request, 'index.html')

@login_required
def Notas(request):
    notas = Nota.objects.filter(usuario=request.user)
    return render(request, 'tablero/notas.html', {'notas': notas})

@login_required
def crearNota(request):
    if request.method == "POST":
        form = NotaForm(request.POST, request.FILES)
        print("Form data:", form.data)
        if form.is_valid():
            nota = form.save(commit=False)
            nota.usuario = request.user            
            nota.save()
            return redirect('notas')
        else:
            print("Form errors:", form.errors)
    else:
        form = NotaForm()        
    return render(request, 'tablero/crear_nota.html', {'form': form})


@login_required
def editarNota(request, id):
    nota = get_object_or_404(Nota, id=id, usuario=request.user)
    if request.method == 'POST':
        form = NotaForm(request.POST, request.FILES, instance=nota)
        if form.is_valid():
            form.save()
            return redirect('notas')
        else:
            print("Formulario no válido:", form.errors)  # Impresión de depuración
    else:
        form = NotaForm(instance=nota)
    return render(request, 'tablero/crear_nota.html', {'form': form, 'nota': nota})



@login_required
def eliminarNota(request, id):
    nota = get_object_or_404(Nota, id=id, usuario=request.user)
    if request.method == 'POST':  # Asegúrate de que la eliminación se haga con un POST
        nota.delete()
        return redirect('notas')
    else:
        # Si no es un POST, puedes redirigir al usuario o mostrar un mensaje de error
        return redirect('notas')

proyectoTablero/apps/usuarios/views.py
from django.contrib.auth import logout as django_logout
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import login, authenticate
from .forms import CustomUserCreationForm, CustomAuthenticationForm

def registro(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # Agregar mensaje de depuración
            print(f"Nuevo usuario creado: {user.username}")
            return redirect('notas')
    else:
        form = CustomUserCreationForm()
    return render(request, 'usuarios/registro.html', {'form': form})


def iniciar_sesion(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('notas')  # Redirigir a la página de notas después del inicio de sesión
    else:
        form = CustomAuthenticationForm()
    return render(request, 'usuarios/iniciar_sesion.html', {'form': form})

def logout(request):
    django_logout(request)
    return redirect('index')  # Redirige a la página de inicio

proyectoTablero/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Codificación de caracteres -->
    <meta charset="UTF-8">
    <!-- Configuración de la pantalla y escalado del 100% -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Documento de estils CSS en la carpeta statci del proyecto -->
    <link rel="stylesheet" href="{% static 'style.css'%}">    

    <!-- Links de bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">

    <!-- Enlazar Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Enlazar FontAwesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    
    <!-- Titulo de la pestaña 
         Este titulo es dinamico en cada
         vista de un html vasta con 
         copiar la etiqueta y cambiar el nombre -->
    <title> {% block titulo %} HOME {% endblock %} </title>
</head>

<body class="body">
    <!-- Navbar de la pagina -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://cdn.glitch.global/91ae3d40-32a1-4ba3-90a8-0e817f46baf3/CienciasPAGE.png?v=1713652399515"
                    alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-around" id="navbarNav">
                <ul class="navbar-nav">
                    <!-- Botón para ir a la página principal -->
                    <li class="nav-item">
                        <a href="{% url 'index' %}" class="btn">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <!-- Botón para ver la lista de las notas -->
                        <a href="{% url 'tablero:notas' %}" class="btn">Mis Notas</a>
                    </li>
                </ul>

                <ul class="navbar-nav">

                </ul>

                <ul class="navbar-nav">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-circle-o fa-3x icon-color" aria-hidden="true"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <!-- Verifica si el usuario está autenticado -->
                            {% if user.is_authenticated %}
                            <!-- Muestra el botón de "Salir" si el usuario está autenticado -->
                            <a class="dropdown-item" href="{% url 'usuarios:logout' %}">Salir de la sesión</a>
                            {% else %}
                            <!-- Muestra las opciones de registro y login si el usuario no está autenticado -->
                            <a class="dropdown-item" href="{% url 'registro' %}">Registrarse</a>
                            <a class="dropdown-item" href="{% url 'login' %}">Ingresar</a>
                            {% endif %}
                        </div>
                    </div>
                </ul>

            </div>
        </div>
    </nav>
    <!-- Navbar de la pagina -->



    {% block home %}
    <section class="jumbotron text-center min-vh-100">
        <div class="main-content">
            <div class="titulo">
                <h1 class="my-4 display-3 fw-bold ls-tight center-vh">
                    Bienvenido a NotaBoard
                </h1>
            </div>
        </div>

        <section id="services" class="services">
            <div class="container">
                <div class="text-center">
                    <h2 class="my-5 display-4 fw-bold ls-tight">Servicios</h2>
                    <!-- <h3 class="section-subheading text-muted"> Explora nuestos servicios </h3> -->
                </div>
                <div class="row text-center">
                    <div class="col-md-6">
                        <img src="https://cdn.glitch.global/91ae3d40-32a1-4ba3-90a8-0e817f46baf3/almacenamiento.png?v=1713480921841"
                            alt="Imagen de Almacenamiento" class="img-fluid">
                        <h4 class="my-3"> Almacenamiento </h4>
                        <p class="text-muted"> Guarda tus notas y accede desde cuaquier dispositivo a ellas </p>
                    </div>
                    <div class="col-md-6">
                        <img src="https://cdn.glitch.global/91ae3d40-32a1-4ba3-90a8-0e817f46baf3/seguridad.png?v=1713480914732"
                            alt="Imagen de Almacenamiento" class="img-fluid">
                        <h4 class="my-3"> Seguridad </h4>
                        <p class="text-muted"> Tus notas siempre estaran seguras </p>
                    </div>
                </div>
            </div>
        </section>
    </section>



    {% endblock %}

    <!-- Este es el contenido dinamico 
        para las diferentes vistas -->
    {% block contenido %}

    {% endblock %}



    <!-- Footer de la pagina -->
    <footer class="sticky-footer">
        <div class="container container d-flex justify-content-center align-items-center h-100">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Diseño de Interfaces 2024</span>
            </div>
        </div>
    </footer>
    <!-- Footer de la pagina -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Scripts de Bootstrap (jQuery primero, luego Popper.js y finalmente Bootstrap.js) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>

proyectoTablero/templates/tablero/crear_nota.html
{% extends "index.html" %}

{% block titulo %} Editar Nota {% endblock %}

{% block home %}

{% endblock %}

{% block contenido %}

<div class="col-lg-12 d-flex align-items-center justify-content-center">
  <h1 class="my-5 display-4 fw-bold ls-tight text-center">
    Agregar Nota <br />
  </h1>
</div>


<div class="card">
  <div class="card-body py-5 px-md-5 min-vh-100">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% if form.errors %}
      <div class="alert alert-danger">
        <strong>¡Error!</strong> Por favor, corrige los siguientes errores:
        {{ form.errors }}
      </div>
      {% endif %}

      <div class="row">
        <div class="col-lg-6">
          <!-- Contenido de la columna izquierda -->
          <div class="form-group text-center align-items-center d-flex flex-column">
            <label for="id_titulo">Titulo:</label>
            {{ form.titulo }}
          </div>
          <div class="form-group text-center align-items-center d-flex flex-column">
            <label for="id_contenido">Contenido:</label>
            {{ form.contenido }}
          </div>
        </div>

        <div class="col-lg-6 mb-4">
          <!-- Contenido de la columna derecha -->
          <div class="div-img form-group text-center align-items-center d-flex flex-column mx-auto">
            <label for="id_imagen">Imagen:</label>
            {{ form.imagen }}
            {% if nota.imagen %}
            <img src="{{ nota.imagen.url }}" alt="Imagen actual" height="100">
            {% endif %}
          </div>
          <div class="form-group text-center align-items-center d-flex flex-column mx-auto">
            <label for="id_color">Color:</label>
            {{ form.color }}
          </div>
        </div>

      </div>


      <div class="save-cambios d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
      </div>
    </form>
  </div>
</div>


{% endblock %}

proyectoTablero/templates/tablero/notas.html
{% extends "index.html" %}

{% block titulo %} Notas {% endblock %}

{% block home %}

{% endblock %}

{% block contenido %}

<script>
  function confirmarEliminacion() {
    return confirm('¿Estás seguro de que quieres eliminar esta nota?');
  }
</script>

<div class="container" style="padding-bottom: 50px;">
  <div class="row justify-content-around mt-4">
    <div class="col-md-8 text-left"> <!-- Columna para el texto a la izquierda -->
      <h2 class="my-8">Aquí están tus notas</h2>
    </div>
    <div class="col-md-4 text-center mt-4"> <!-- Columna para el enlace "Crear Nota" en el medio -->
      <a href="{% url 'tablero:crear_nota' %}" class="btn btn-primary">Crear Nota</a>
    </div>
  </div>


  {% if notas %}
  <div class="row justify-content-center">
    {% for nota in notas %}
    <div class="col-md-6 mb-4">
      <!--   EA9E19 54ea19 19b6ea -->
      <div class="card card-notas border m-3" style="background-color: {{ nota.color }};">
        {% if nota.imagen %}
        <img src="{{ nota.imagen.url }}" class="card-img-top" alt="Imagen de la nota">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ nota.titulo }}</h5>
          <p class="card-text">{{ nota.contenido }}</p>
          <!-- Botones de opciones -->
          <div class="text-center">
            <a href="{% url 'tablero:editar_nota' nota.id %}" class="btn btn-primary">Editar</a>
            <!-- Formulario de eliminación -->
            <form action="{% url 'tablero:eliminar_nota' nota.id %}" method="post" style="display: inline;"
              onsubmit="return confirmarEliminacion();">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Eliminar</button>
            </form>
          </div>
          <!-- Botones de opciones -->
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="row justify-content-center mt-4">
    <div class="col-md-6">
      <p class="text-center">No hay notas disponibles.</p>
    </div>
  </div>
  {% endif %}
</div>


{% endblock %}

proyectoTablero/templates/usuarios/iniciar_sesion.html
{% extends "index.html" %}

{% block titulo %} Iniciar Sesión {% endblock %}

{% block home %}

{% endblock %}

{% block contenido %}
<!-- Section: Design Block -->
<section class="login-sec">
    <!-- Jumbotron -->
    <div class="px-4 py-5 px-md-5 text-center text-lg-start min-vh-100" style="background-color: hsl(0, 0%, 96%)">
        <div class="container">
            <div class="row gx-lg-5 align-items-center">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <h1 class="my-5 display-3 fw-bold ls-tight">
                        Iniciar Sesión <br />
                        <span class="text-primary">Ingresa tus datos</span>
                    </h1>
                    <p style="color: hsl(217, 10%, 50.8%)">
                        Por favor, ingresa tu nombre de usuario y contraseña para iniciar sesión.
                    </p>
                </div>

                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="card">
                        <div class="card-body py-5 px-md-5">
                            <form method="post">
                                {% csrf_token %}
                                <!-- Nombre de Usuario -->
                                <div class="row mb-4">
                                    <div class="col-md-12">
                                        <div data-mdb-input-init class="form-outline">
                                            <input type="text" id="id_username" name="username" class="form-control"
                                                value="{{ form.username.value }}" required>
                                            <label class="form-label" for="id_username">Nombre de Usuario</label>
                                        </div>
                                    </div>
                                </div>

                                <!-- Contraseña -->
                                <div class="row mb-4">
                                    <div class="col-md-12">
                                        <div data-mdb-input-init class="form-outline">
                                            <input type="password" id="id_password" name="password" class="form-control"
                                                required>
                                            <label class="form-label" for="id_password">Contraseña</label>
                                        </div>
                                    </div>
                                </div>

                                <!-- Botón de Iniciar Sesión -->
                                <div class="text-center">
                                    <button type="submit" data-mdb-button-init data-mdb-ripple-init
                                        class="btn btn-primary btn-block mb-4">
                                        Iniciar Sesión
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

proyectoTablero/templates/usuarios/registro.html
{% extends "index.html" %}


{% block titulo %} Registro {% endblock %}

{% block home %}

{% endblock %}


{% block contenido %}

<section class="registrarse">
  <div class="px-4 py-5 px-md-5 text-center text-lg-start min-vh-100" style="background-color: hsl(0, 0%, 96%)">
    <div class="container">
      <div class="row gx-lg-5 align-items-center">
        <div class="col-lg-6 mb-5 mb-lg-0">
          <h1 class="my-5 display-3 fw-bold ls-tight">
            Registro de Usuario <br />
            <span class="text-primary">Completa tus datos</span>
          </h1>
          <p style="color: hsl(217, 10%, 50.8%)">
            Por favor, ingresa la siguiente información para registrarte.
          <div class="col-md-12 mt-2">
            <div class="text-muted">Instrucciones de contraseña:</div>
            <ul class="text-muted">
              <li>Debe tener al menos 8 caracteres.</li>
              <li>Debe incluir al menos una mayúscula.</li>
              <li>Debe incluir al menos un número.</li>
            </ul>
          </div>
          </p>
        </div>

        <div class="col-lg-6 mb-5 mb-lg-0">
          <div class="card">
            <div class="card-body py-5 px-md-5">
              <form method="post">
                {% csrf_token %}
                <!-- Nombre de Usuario -->
                <div class="row mb-4">
                  <div class="col-md-12">
                    <div data-mdb-input-init class="form-outline">
                      <input type="text" id="id_username" name="username" class="form-control"
                        value="{{ form.username.value }}" required>
                      <label class="form-label" for="id_username">Nombre de Usuario</label>
                    </div>
                  </div>
                </div>

                <!-- Nombre -->
                <div class="row mb-4">
                  <div class="col-md-6">
                    <div data-mdb-input-init class="form-outline">
                      <input type="text" id="id_nombre" name="nombre" class="form-control"
                        value="{{ form.nombre.value }}" required>
                      <label class="form-label" for="id_nombre">Nombre</label>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div data-mdb-input-init class="form-outline">
                      <input type="text" id="id_apellido" name="apellido" class="form-control"
                        value="{{ form.apellido.value }}" required>
                      <label class="form-label" for="id_apellido">Apellido</label>
                    </div>
                  </div>
                </div>

                <!-- Fecha de Nacimiento -->
                <div class="row mb-4">
                  <div class="col-md-12">
                    <div data-mdb-input-init class="form-outline">
                      <input type="date" id="id_fecha_nacimiento" name="fecha_nacimiento" class="form-control"
                        value="{{ form.fecha_nacimiento.value }}">
                      <label class="form-label" for="id_fecha_nacimiento">Fecha de Nacimiento</label>
                    </div>
                  </div>
                </div>

                <!-- Email -->
                <div class="row mb-4">
                  <div class="col-md-12">
                    <div data-mdb-input-init class="form-outline">
                      <input type="email" id="id_email" name="email" class="form-control" value="{{ form.email.value }}"
                        required>
                      <label class="form-label" for="id_email">Correo Electrónico</label>
                    </div>
                  </div>
                </div>

                <!-- Contraseña -->
                <div class="row mb-4">
                  <div class="col-md-6">
                    <div data-mdb-input-init class="form-outline">
                      <input type="password" id="id_password1" name="password1" class="form-control" required>
                      <label class="form-label" for="id_password1">Contraseña</label>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div data-mdb-input-init class="form-outline">
                      <input type="password" id="id_password2" name="password2" class="form-control" required>
                      <label class="form-label" for="id_password2">Confirmar Contraseña</label>
                    </div>
                    {% if form.errors.password2 %}
                    <small class="text-danger">{{ form.errors.password2 }}</small>
                    {% endif %}
                  </div>
                </div>
                <!-- Botón de Registro -->
                <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">
                  Registrarse
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}